name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1  # v2 does not have submodules option now
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.62.2'
          # extended: true

      - name: Build
        run: hugo --minify
      
      - name: Deploy
        run: |
            cd public
            git config --global user.email "${{ secrets.EMAIL }}"
            git config --global user.name "${{ secrets.NAME }}"
            git add -A
            git commit -am"Build via GitHub action"
            git push origin master
